# Generated by Django 5.0.4 on 2024-05-02 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights_schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('city', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='flight',
            name='arrival_city',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='departure_city',
        ),
        migrations.AddField(
            model_name='flight',
            name='destination',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='arrivals', to='flights_schedule.airport'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='origin',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='departures', to='flights_schedule.airport'),
            preserve_default=False,
        ),
    ]
